include "app.conf"

play.server.http.port = ${app.backend.port}

play.filters.enabled = ["play.filters.cors.CORSFilter"]
play.modules.enabled += "modules.DatabaseModule"

db.default.driver   = org.postgresql.Driver
db.default.url      = "jdbc:postgresql://localhost:5432/moviedb"
db.default.username = "your-username"
db.default.password = "your-password"

play.filters.cors {
  allowedOrigins = [${app.frontend.frontendurl}]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "Authorization"]
}